### ISSUE TITLE
Test Phase Dice Scores

### ISSUE THREAD

**Issue by tarekegn82** [himashi92/vizviva_brats_2021#12]
Dear @himashi92 

After running test experiments, I only found segmentation mask under segs folder. I would like to know how to get the dice scores of each tumor class as presented in this paper. Please kindly respond with the necessary details.

thank you

**Comment by himashi92** [comment]
Hi,

The test.py script is written in a way that handles the inference of the online brats challenge where we do not get to see ground truths. If you have groundtruths for the test dataset, use the generate_segmentations function in the utils.py script: *https://github.com/himashi92/vizviva_brats_2021/blob/main/utils.py#L218**.

Cheers,
Himashi

**Comment by tarekegn82** [comment]
![writer](https://github.com/himashi92/vizviva_brats_2021/assets/66314519/1e569bd5-1600-4fc7-afcb-4660918f1985)
After importing generate_segmentations from the utils.py file, I tried to use the function inside test.py main function. The `writer is not defined` error occurs when I include it inside the generate_segmentations function inside the test.py main. Also, when I remove it, the attached error occurs. Are there any other suggestions that can help me resolve this error? also can you provide an updated test.py when you have time, please?
@himashi92
