### ISSUE TITLE
dice

### ISSUE THREAD

**Issue by H-CODE6** [himashi92/vizviva_brats_2021#2]
Hello, how to evaluate the Dice coefficient after the test?

**Comment by himashi92** [comment]
Hello,

You can use the function in https://github.com/himashi92/vizviva_brats_2021/blob/main/utils.py#L132 to evaluate predictions.

**Comment by H-CODE6** [comment]
Hello, I didn't find test.py in the code folder , can you provide it?

**Comment by himashi92** [comment]
Added test.py to the repository.

**Comment by tarekegn82** [comment]
Hello Dear @H-CODE6 

Have you solved this issue yet? If you did I need your suggestions. Thank you
