### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by H-CODE6** [himashi92/vizviva_brats_2021#3]
Hello, I didn't find test.py in the code folder , can you provide it?

**Comment by himashi92** [comment]
Added test.py to the repository.

**Comment by H-CODE6** [comment]
Thank you for your reply. I can't run train.py successfully according to your command python train.py --num_classes 3 --epochs 350 , is there any change in the running code? Or do you need to change the code in the train.py?

**Comment by himashi92** [comment]
What is the error you are getting?

**Comment by H-CODE6** [comment]
usage: train.py [-h] [-a ARCH] [--width WIDTH] [-j N] [--start-epoch N]
                [--epochs N] [-b N] [--lr LR] [--lr_dis LR_DIS] [--wd W]
                [--resume PATH] [--devices DEVICES] [--seed SEED] [--warmup N]
                [--disable-cos] [--warm WARM] [--val VAL] [--fold FOLD]
                [--norm_layer NORM_LAYER] [--optim {adam,sgd,adamw}]
                [--com COM] [--dropout DROPOUT] [--warm_restart] [--full]
                [--lambda_adv LAMBDA_ADV] [--lambda_vat LAMBDA_VAT]
train.py: error: unrecognized arguments: --num_classes 3
Do you need to make changes to run the code?

**Comment by himashi92** [comment]
Try the latest code without the argument num_classes.

**Comment by H-CODE6** [comment]
NameError: name 'KFold' is not defined after operation，The code in train.py should need to be updated

**Comment by H-CODE6** [comment]
The code in utils.py and train.py should need to be updated

**Comment by H-CODE6** [comment]
The code in brats.py and train.py should need to be updated

**Comment by himashi92** [comment]
I updated the repo. Can you check now?

**Comment by H-CODE6** [comment]
The training code should be available. Thank you very much for your answer. If you continue to have questions, please ask you again? Thank you again.

**Comment by H-CODE6** [comment]
Hello, I'm reproducing your code. Please tell me that the number of brats2021 in the training set and tested in config is inconsistent with that in the running process. I put 330 data in my valid and only 77 Val during training. Why?

**Comment by H-CODE6** [comment]
Hello, the author. I'm running your code. I put 770 data in the training process. During the training process, I found that it was divided into two parts. There was a separate copy of more than 70 data. I started training after running several epochs. How do you understand this? Why divide according to such proportion?

**Comment by himashi92** [comment]
I splitted dataset into training and validation datasets. Validation dataset is used to evaluate model's performance over unseen data during training. Based on performance, I save the best model. 

Please follow Kfold function https://github.com/himashi92/vizviva_brats_2021/blob/main/dataset/brats_train.py#L96.

**Comment by H-CODE6** [comment]
OK, why is the training set split? Can't the valid verification set be directly used to test the performance?

**Comment by himashi92** [comment]
Ground truth masks for the validation dataset are not yet released. You can use the BraTS continuous evaluation portal to evaluate your predictions on the BraTS 2021 validation dataset.

**Comment by H-CODE6** [comment]
OK, can you provide me with the address of the brats evaluation website?

**Comment by himashi92** [comment]
https://www.synapse.org/#!Synapse:syn27046444/wiki/616991

**Comment by H-CODE6** [comment]
Hello, just run test Py, the error of AttributeError: 'Namespace' object has no attribute 'lambda_adv'
 appears. What is the reason?

**Comment by H-CODE6** [comment]
After adding parser.add_argument('--lambda_adv', type=float, default=0.3, help='scalar constant adversarial loss')
parser.add_argument('--lambda_vat', type=float, default=0.2, help='scalar constant vat loss')，The error also appears RuntimeError: Exception thrown in SimpleITK ReadImage: /tmp/SimpleITK/Code/IO/src/sitkImageReaderBase.cxx:99:
sitk::ERROR: The file "/media/hkw/hkwdisk/vizviva_brats_2021-main/BRATS2021/Data/valid/BraTS2021_00011_t1.nii.gz" does not exist.
There should be brats2021 after valid_ 00011 this question folder
Can you update test.py code

**Comment by himashi92** [comment]
This test.py code is written according to the brats evaluation. You can modify it in the way you want.
