### ISSUE TITLE
prediction

### ISSUE THREAD

**Issue by billel-a** [himashi92/vizviva_brats_2021#6]
Hi, i used the test.py with the pretrained model that you posted in your git but i got an error, can you please help me fix it 
![image](https://user-images.githubusercontent.com/57478220/164415968-14ee8246-a9ce-4da0-bd68-8f9fd3bc0468.png)
![image](https://user-images.githubusercontent.com/57478220/164414930-e6ad6fe3-f782-438f-9d57-ac92b0fc0eb1.png)

**Comment by himashi92** [comment]
I updated the code by adding norm_layer as group and width as 48. Can you check now?

**Comment by billel-a** [comment]
Thanks alot, the previous error was fixed but i got another error
![image](https://user-images.githubusercontent.com/57478220/164747448-b55971f5-9cf0-4fff-b752-0414d0f7376e.png)

**Comment by himashi92** [comment]
That code line is unwanted. I updated the script.
