### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by H-CODE6** [himashi92/vizviva_brats_2021#8]
Hello, the author, recently reading your vizviva_ Brats_ 2021 code, found in brats_ When validating in the train, add the patient as the above training code_ Image, patient_ Label = pad_ Or_ Crop_ Image (patient_image, patient\u label, target\u size= (128, 128, 128)), I found that the performance decreased a lot. I don't know why.

**Comment by himashi92** [comment]
Hello, can you explain your problem a bit more?

**Comment by H-CODE6** [comment]
OK, thank you very much for your reply. I've been studying your code recently.brats_train.py in dataset folder , I found that only patient_image, patient_label = pad_or_crop_image(patient_image, patient_label, target_size=(128, 128, 128)) was added in training, but not in val. therefore, I also added patient_image, patient_label = pad_or_crop_image(patient_image, patient_label, target_size=(128, 128, 128)). I found that the performance decreased greatly. I don't know why? Did you cut out the core area when cutting? Or any other reason, looking forward to your reply.

**Comment by himashi92** [comment]
Hi, during validation you have to consider the entire MRI volume, not just cropped(128x128x128) and padded patch. We cut unnecessary background pixels as we need to learn more features of the region of interest, during training. That's why I used the crop_and_pad function only during training.

**Comment by H-CODE6** [comment]
Thank you very much for your reply. I'd like to ask you if you want to unify the size to 128*128*128 during verification, so that you can enter the model. Is there any method you can use and any distress? I look forward to your reply.

**Comment by himashi92** [comment]
Why do you need to crop the input during verification? I still don't understand your question here :)

**Comment by H-CODE6** [comment]
Hello, author. In your paper, I found that you finally ran 100epoch to train. Would you please tell me why you chose 100epoch?
